name: 'My Custom Action'
description: 'Sets up Node.js, installs dependencies, and builds the project'
inputs:
  node-version:
    description: 'Node.js version'
    required: true
    default: '20.x'
runs:
  using: "composite" # Defines this as a composite action
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install Dependencies
      run: npm ci
      shell: bash
    - name: Build Project
      run: npm run build
      shell: bash