name: Node.js CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    uses: ./.github/workflows/nodejs-test.yml
    with:
      node-version: '20.x'
  build:
    runs-on: ubuntu-latest
    needs: run-tests
    # This job ONLY runs for pushes to the main branch, not for pull requests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - name: Run my custom build action
        uses: ./.github/actions/my_action
        with:
          node-version: '20.x'  

      - name: Upload the package
        uses: actions/upload-artifact@v4
        with:
          name: node-app-package
          path: release.zip
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: production
      url: https://example.com
    steps:
    - name: Download the package
      uses: actions/download-artifact@v4
      with:
        name: node-app-package
    - name: "Simulate deployment"
      run: |
        echo "Deployed to production"
        ls -la
        echo "Deployment successfull"
